# @author DieFriiks / CustomCraftDev / undeaD_D
# @link www.custom-craft.de
# @github https://github.com/CustomCraftDev/perplayercommands

debug: true
custom-cmd: testing
msg-color: YELLOW
default-msg: the default message
nopermission-msg: You shall not pass !!!
nopermission-color: RED
debug-color: RED
infoonly:
  var1: '%playername% gets replaced with the name of the player'
  var2: '%world% gets replaced with the world the player is currently in'
  var3: '%nextline% indicates a new line in the chat'
  var5: '%no% indicates that there should be nothing to be displayed'
players:
  undeaD_D: '[WARNING]%nextline%Developer incoming !!!%nextline%[WARNING]'
  Notch: why you sell minecraft -.-
  Steve: FAKER !!!
